#application: cruncho
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: main.app


libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.2.3"
- name: webapp2
  version: "2.5.2"
- name: numpy
  version: "latest"


skip_files:
- env
- .git
- \.gitignore
- ^\.git/.*
- ^ (. * /)? #. * # $
- ^ (. * /)?. * ~ $
- ^ (. * /)?. * \. py [co] $
- ^ (. * /)?. * / RCS /.*$
- ^ (. * /)? \ .. * $