#application: cruncho-images
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
#- url: /api/v1/
#  script: images.img.application
#- url: /.*
#  script: images.img.application

libraries:
- name: django
  version: "latest"
- name: PIL
  version: "1.1.7"
- name: webob
  version: "latest"
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest
skip_files:
- env/
- lib/
- tornado/
- settings/

